language: node_js

node_js:
  - lts/*
os:
  - windows
  - linux
  - osx

env:
  - ELECTRON_RUN_AS_NODE="1"

before_install:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then chmod +x ./test.sh; fi

install:
  - node keygen
  - node js2c
  - npm install
script:
  - npm run build
  - node pack
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then ./test/electron ./test/resources/app.asar; else test\electron.exe test\resources\app.asar; fi
